// <auto-generated />
namespace MyContosoUniversity.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RowVersion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RowVersion));
        
        string IMigrationMetadata.Id
        {
            get { return "201402221422482_RowVersion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
